### ISSUE TITLE
deadlock

### ISSUE THREAD

**Issue by yannick** [tamediadigital/kafka-d#13]
if the producer goes down and/or the connection is capped there is a deadlock

at least here:
https://github.com/tamediadigital/kafka-d/blob/master/source/kafkad/producer.d#L218

but possible at other places aswell.

expected behaviour:
the client should not care, if the connection drops, kafka-d should re-establish it

**Comment by pszturmaj** [comment]
Please recheck and close the issue if it works now.

**Comment by yannick** [comment]
works! :dancers:
